// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.1
// source: jobworker.proto

package jobworker_data

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkerStartRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Command []string `protobuf:"bytes,1,rep,name=command,proto3" json:"command,omitempty"`
}

func (x *WorkerStartRequest) Reset() {
	*x = WorkerStartRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jobworker_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkerStartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerStartRequest) ProtoMessage() {}

func (x *WorkerStartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jobworker_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerStartRequest.ProtoReflect.Descriptor instead.
func (*WorkerStartRequest) Descriptor() ([]byte, []int) {
	return file_jobworker_proto_rawDescGZIP(), []int{0}
}

func (x *WorkerStartRequest) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

type WorkerStopRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobId string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
}

func (x *WorkerStopRequest) Reset() {
	*x = WorkerStopRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jobworker_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkerStopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerStopRequest) ProtoMessage() {}

func (x *WorkerStopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jobworker_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerStopRequest.ProtoReflect.Descriptor instead.
func (*WorkerStopRequest) Descriptor() ([]byte, []int) {
	return file_jobworker_proto_rawDescGZIP(), []int{1}
}

func (x *WorkerStopRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type WorkerQueryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobId string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
}

func (x *WorkerQueryRequest) Reset() {
	*x = WorkerQueryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jobworker_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkerQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerQueryRequest) ProtoMessage() {}

func (x *WorkerQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jobworker_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerQueryRequest.ProtoReflect.Descriptor instead.
func (*WorkerQueryRequest) Descriptor() ([]byte, []int) {
	return file_jobworker_proto_rawDescGZIP(), []int{2}
}

func (x *WorkerQueryRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type WorkerLogRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobId string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
}

func (x *WorkerLogRequest) Reset() {
	*x = WorkerLogRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jobworker_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkerLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerLogRequest) ProtoMessage() {}

func (x *WorkerLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jobworker_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerLogRequest.ProtoReflect.Descriptor instead.
func (*WorkerLogRequest) Descriptor() ([]byte, []int) {
	return file_jobworker_proto_rawDescGZIP(), []int{3}
}

func (x *WorkerLogRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type WorkerStartResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobId string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
}

func (x *WorkerStartResponse) Reset() {
	*x = WorkerStartResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jobworker_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkerStartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerStartResponse) ProtoMessage() {}

func (x *WorkerStartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jobworker_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerStartResponse.ProtoReflect.Descriptor instead.
func (*WorkerStartResponse) Descriptor() ([]byte, []int) {
	return file_jobworker_proto_rawDescGZIP(), []int{4}
}

func (x *WorkerStartResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type WorkerStopResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *WorkerStopResponse) Reset() {
	*x = WorkerStopResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jobworker_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkerStopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerStopResponse) ProtoMessage() {}

func (x *WorkerStopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jobworker_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerStopResponse.ProtoReflect.Descriptor instead.
func (*WorkerStopResponse) Descriptor() ([]byte, []int) {
	return file_jobworker_proto_rawDescGZIP(), []int{5}
}

type WorkerQueryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobId  string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *WorkerQueryResponse) Reset() {
	*x = WorkerQueryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jobworker_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkerQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerQueryResponse) ProtoMessage() {}

func (x *WorkerQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jobworker_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerQueryResponse.ProtoReflect.Descriptor instead.
func (*WorkerQueryResponse) Descriptor() ([]byte, []int) {
	return file_jobworker_proto_rawDescGZIP(), []int{6}
}

func (x *WorkerQueryResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *WorkerQueryResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type WorkerLogResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobId string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Log   string `protobuf:"bytes,2,opt,name=log,proto3" json:"log,omitempty"`
}

func (x *WorkerLogResponse) Reset() {
	*x = WorkerLogResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jobworker_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkerLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerLogResponse) ProtoMessage() {}

func (x *WorkerLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jobworker_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerLogResponse.ProtoReflect.Descriptor instead.
func (*WorkerLogResponse) Descriptor() ([]byte, []int) {
	return file_jobworker_proto_rawDescGZIP(), []int{7}
}

func (x *WorkerLogResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *WorkerLogResponse) GetLog() string {
	if x != nil {
		return x.Log
	}
	return ""
}

var File_jobworker_proto protoreflect.FileDescriptor

var file_jobworker_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x6a, 0x6f, 0x62, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x04, 0x6d, 0x61, 0x69, 0x6e, 0x22, 0x2e, 0x0a, 0x12, 0x57, 0x6f, 0x72, 0x6b, 0x65,
	0x72, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07,
	0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x22, 0x2a, 0x0a, 0x11, 0x57, 0x6f, 0x72, 0x6b, 0x65,
	0x72, 0x53, 0x74, 0x6f, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06,
	0x6a, 0x6f, 0x62, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6a, 0x6f,
	0x62, 0x49, 0x64, 0x22, 0x2b, 0x0a, 0x12, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x6a, 0x6f, 0x62,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6a, 0x6f, 0x62, 0x49, 0x64,
	0x22, 0x29, 0x0a, 0x10, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x6a, 0x6f, 0x62, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6a, 0x6f, 0x62, 0x49, 0x64, 0x22, 0x2c, 0x0a, 0x13, 0x57,
	0x6f, 0x72, 0x6b, 0x65, 0x72, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x6a, 0x6f, 0x62, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x6a, 0x6f, 0x62, 0x49, 0x64, 0x22, 0x14, 0x0a, 0x12, 0x57, 0x6f, 0x72,
	0x6b, 0x65, 0x72, 0x53, 0x74, 0x6f, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x44, 0x0a, 0x13, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x6a, 0x6f, 0x62, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6a, 0x6f, 0x62, 0x49, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x3c, 0x0a, 0x11, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x4c,
	0x6f, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x6a, 0x6f,
	0x62, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6a, 0x6f, 0x62, 0x49,
	0x64, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6f, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6c, 0x6f, 0x67, 0x32, 0x8d, 0x02, 0x0a, 0x06, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x12, 0x3e,
	0x0a, 0x07, 0x4a, 0x6f, 0x62, 0x53, 0x74, 0x6f, 0x70, 0x12, 0x17, 0x2e, 0x6d, 0x61, 0x69, 0x6e,
	0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x53, 0x74, 0x6f, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x18, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72,
	0x53, 0x74, 0x6f, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x41,
	0x0a, 0x08, 0x4a, 0x6f, 0x62, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x18, 0x2e, 0x6d, 0x61, 0x69,
	0x6e, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x57, 0x6f, 0x72, 0x6b,
	0x65, 0x72, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x41, 0x0a, 0x08, 0x4a, 0x6f, 0x62, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x18, 0x2e,
	0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x57,
	0x6f, 0x72, 0x6b, 0x65, 0x72, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x3d, 0x0a, 0x06, 0x4a, 0x6f, 0x62, 0x4c, 0x6f, 0x67, 0x12, 0x16,
	0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x57, 0x6f,
	0x72, 0x6b, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x30, 0x01, 0x42, 0x10, 0x5a, 0x0e, 0x6a, 0x6f, 0x62, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72,
	0x2e, 0x64, 0x61, 0x74, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_jobworker_proto_rawDescOnce sync.Once
	file_jobworker_proto_rawDescData = file_jobworker_proto_rawDesc
)

func file_jobworker_proto_rawDescGZIP() []byte {
	file_jobworker_proto_rawDescOnce.Do(func() {
		file_jobworker_proto_rawDescData = protoimpl.X.CompressGZIP(file_jobworker_proto_rawDescData)
	})
	return file_jobworker_proto_rawDescData
}

var file_jobworker_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_jobworker_proto_goTypes = []interface{}{
	(*WorkerStartRequest)(nil),  // 0: main.WorkerStartRequest
	(*WorkerStopRequest)(nil),   // 1: main.WorkerStopRequest
	(*WorkerQueryRequest)(nil),  // 2: main.WorkerQueryRequest
	(*WorkerLogRequest)(nil),    // 3: main.WorkerLogRequest
	(*WorkerStartResponse)(nil), // 4: main.WorkerStartResponse
	(*WorkerStopResponse)(nil),  // 5: main.WorkerStopResponse
	(*WorkerQueryResponse)(nil), // 6: main.WorkerQueryResponse
	(*WorkerLogResponse)(nil),   // 7: main.WorkerLogResponse
}
var file_jobworker_proto_depIdxs = []int32{
	1, // 0: main.Worker.JobStop:input_type -> main.WorkerStopRequest
	0, // 1: main.Worker.JobStart:input_type -> main.WorkerStartRequest
	2, // 2: main.Worker.JobQuery:input_type -> main.WorkerQueryRequest
	3, // 3: main.Worker.JobLog:input_type -> main.WorkerLogRequest
	5, // 4: main.Worker.JobStop:output_type -> main.WorkerStopResponse
	4, // 5: main.Worker.JobStart:output_type -> main.WorkerStartResponse
	6, // 6: main.Worker.JobQuery:output_type -> main.WorkerQueryResponse
	7, // 7: main.Worker.JobLog:output_type -> main.WorkerLogResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_jobworker_proto_init() }
func file_jobworker_proto_init() {
	if File_jobworker_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_jobworker_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkerStartRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jobworker_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkerStopRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jobworker_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkerQueryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jobworker_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkerLogRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jobworker_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkerStartResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jobworker_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkerStopResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jobworker_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkerQueryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jobworker_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkerLogResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_jobworker_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_jobworker_proto_goTypes,
		DependencyIndexes: file_jobworker_proto_depIdxs,
		MessageInfos:      file_jobworker_proto_msgTypes,
	}.Build()
	File_jobworker_proto = out.File
	file_jobworker_proto_rawDesc = nil
	file_jobworker_proto_goTypes = nil
	file_jobworker_proto_depIdxs = nil
}
